_wandb:
    value:
        cli_version: 0.18.1
        m: []
        python_version: 3.12.6
        t:
            "1":
                - 1
                - 41
                - 55
                - 105
            "2":
                - 1
                - 41
                - 55
                - 105
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.6
            "5": 0.18.1
            "8":
                - 5
            "12": 0.18.1
            "13": darwin-arm64
architecture_description:
    value: Conv(1, 32, 3x3).ReLU().MaxPool(2x2) -> Conv(32, 64, 3x3).ReLU().MaxPool(2x2) -> FC(64*7*7, 128).ReLU() -> FC(128, 10)
epochs:
    value: 2
learning_rate:
    value: 0.005
